added cohortId to student table
digital-futures-academy/atlas-api pull request #10
Opened 2021-08-17 16:41 UTC by richardtully

Problem: Students are currently not associated with a cohort

Solution: add a column called cohortId to the student table

Jira link: https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-28

2021-08-17 16:50 UTC, richardtully commented
James co-authored this - forgot to add him to the commit.

2021-08-17 17:13 UTC, dearshrewdwit requested changes
Nice.

Currently the convention looks like foreign keys are capitalised

> eg: https://github.com/digital-futures-academy/atlas-api/blob/main/migrations/20210816155020-create-module-challenge.js#L11

Do you need sequelize associations, or just the foreign key?

2021-08-18 08:10 UTC, Reginmaru approved these changes

2021-08-18 08:25 UTC, richardtully commented
We've changed the responsibility of this task to someone else - teething problems!

2021-08-18 08:25 UTC, closed without merging