AT-29
digital-futures-academy/atlas-api pull request #13
Opened 2021-08-19 17:40 UTC by AamirahV

Problem:

Solution:

Jira Issue:

2021-08-31 11:30 UTC, dearshrewdwit commented
@AamirahV You need to update this branch

2021-08-31 11:42 UTC, dearshrewdwit requested changes
Nearly there.

1 see comment about the sequelize query.
2. Why is there work on this PR that has already been merged?

2021-08-31 11:42 UTC, dearshrewdwit commented on routes/cohorts.js
> +  const students = await Student.findAndCountAll({
Can you make one query instead? https://sequelize.org/master/manual/eager-loading.html#ordering-eager-loaded-associations

Something like:
```js
const cohort = await Cohort.findOne({
  where: { id: req.params.id },
  include: { all: true },
  order: [Student, 'firstName', 'ASC']
})
```
You should be able to access the data you need, and just send back the response as
(abridged for demo purposes)
```json
{ 
  "cohort": {
    "id":  4,
    "name": "mse-2106-a",
    "students": [
      {
         "id": 3,
         "firstName": "aaa"
      },
    ]
  }
}
```

2021-09-01 09:59 UTC, dearshrewdwit requested changes
Nice. Some minor changes.

1. What happens to the data already in production database where the cohorts don't have a lead instructor?

2021-09-01 09:59 UTC, dearshrewdwit commented on routes/cohorts.js
> +  const cohort = await Cohort.findAndCountAll({
the var name represents a set of cohorts - so let's name it `cohorts`

2021-09-01 09:59 UTC, dearshrewdwit commented on routes/cohorts.js
> +      model: Student},
Why specify `model: Student`, when you also specify  `{ all: true }`

It's like having a bowl of apples, oranges, bananas, and saying can you get me all the fruit and the bananas!

2021-09-01 09:59 UTC, dearshrewdwit commented on routes/cohorts.js
> +      id: req.params.id},
the linebreaks are out of sync here

2021-09-01 09:59 UTC, dearshrewdwit commented on routes/cohorts.js
> +  const cohort = await Cohort.findAndCountAll({
Is there a reason to use `findAndCountAll` over `findAll` ?

2021-09-01 10:03 UTC, AamirahV commented
> Nice. Some minor changes.
> 
> 1. What happens to the data already in production database where the cohorts don't have a lead instructor?

returns null atm

2021-09-01 10:05 UTC, AamirahV commented on routes/cohorts.js
> +  const cohort = await Cohort.findAndCountAll({
the count all returns a student count

2021-09-01 10:06 UTC, dearshrewdwit commented
> > Nice. Some minor changes.
> > 
> > 1. What happens to the data already in production database where the cohorts don't have a lead instructor?
> 
> returns null atm

To avoid this, write a second migration to add a lead instructor to the cohorts that already exist so we avoid null fields -> which will cause problems if the frontend expects that data to exist.

Does that make sense?

2021-09-01 10:15 UTC, AamirahV commented on routes/cohorts.js
> +      model: Student},
sorry i forgot to take it out as i was trying some different methods

2021-09-01 10:24 UTC, AamirahV commented
> > > Nice. Some minor changes.
> > > 
> > > 1. What happens to the data already in production database where the cohorts don't have a lead instructor?
> > 
> > 
> > returns null atm
> 
> To avoid this, write a second migration to add a lead instructor to the cohorts that already exist so we avoid null fields -> which will cause problems if the frontend expects that data to exist.
> 
> Does that make sense?

sort of. so i would be assigning a default lead coach to the cohorts without a lead instructor?

2021-09-01 10:56 UTC, dearshrewdwit commented
> > > > Nice. Some minor changes.
> > > > 
> > > > 1. What happens to the data already in production database where the cohorts don't have a lead instructor?
> > > 
> > > 
> > > returns null atm
> > 
> > 
> > To avoid this, write a second migration to add a lead instructor to the cohorts that already exist so we avoid null fields -> which will cause problems if the frontend expects that data to exist.
> > Does that make sense?
> 
> sort of. so i would be assigning a default lead coach to the cohorts without a lead instructor?

In a real example, you would have to find the correct coach name for the correct cohort. So let's simulate it.

There are 2 cohorts currently:

```sh
 id |    name    |           createdAt           |           updatedAt           |       startDate        
----+------------+-------------------------------+-------------------------------+------------------------
  2 | mse-2103-a | 2021-08-23 12:36:15.197566+00 | 2021-08-23 12:36:15.197566+00 | 2021-03-01 00:00:00+00
  3 | mse-2106-a | 2021-08-23 12:36:49.156668+00 | 2021-08-23 12:36:49.156668+00 | 2021-06-28 00:00:00+00
```
for cohort id 2, add a lead coach name: 'Edward Withers'
for cohort id 3, add a lead coach name: 'Edward's evil twin'

2021-09-02 17:11 UTC, dearshrewdwit reviewed
Fix style rules - then should be good to go

2021-09-02 19:06 UTC, closed without merging