At 13 File Uploader
digital-futures-academy/atlas-api pull request #20
Opened 2021-08-24 13:01 UTC by OllieVanD

Created file uploader with routers and 4 classes to handle csv file with validation checks Unit tested with jasmine and feature tested with cypress.

2021-08-24 13:38 UTC, dearshrewdwit requested changes
Good work so far.

Move the eslint addition to its own PR and resolve some of the questions below in comments. Additionally

Write some test cases that cover:

- What would happen uploading a csv with malformed headers? No headers?
- What happens if one of the text fields for the learning self assessment is beyond the dB constraint for character length?

2021-08-24 13:38 UTC, dearshrewdwit commented on .eslintrc.js
> +module.exports = {
Nice idea. Let's move this to its own PR, however.

2021-08-24 13:38 UTC, dearshrewdwit commented on cypress/support/commands.js
> +Cypress.Commands.add('form_request', ( method, url, formData, done) => {
What's the reason for this command? Where is it used?

2021-08-24 13:38 UTC, dearshrewdwit commented on package.json
> +  },
These should be added in a separate PR with eslint

2021-08-24 13:38 UTC, dearshrewdwit commented on package.json
> +    "csv-parser": "^3.0.0",
Where is this dependency used?

2021-08-24 13:38 UTC, dearshrewdwit commented on src/fileUpload.js
> +      return this.errors
What's the reasoning behind  explicitly returning from this function? I don't see it used in the controller action

2021-08-24 13:38 UTC, dearshrewdwit commented on src/fileUpload.js
> +      this.status = 'Success'
What's the reasoning behind setting the status property? I don't see it used in the response object

2021-08-24 13:46 UTC, OllieVanD commented on src/fileUpload.js
> +      this.status = 'Success'
This is something that we use for AT-34 branch, must have just been put on this branch by accident.

2021-08-24 13:51 UTC, OllieVanD commented on cypress/support/commands.js
> +Cypress.Commands.add('form_request', ( method, url, formData, done) => {
Fixed

2021-08-24 13:52 UTC, OllieVanD commented on package.json
> +  },
Can you elaborate with what you mean by this?

2021-08-24 13:54 UTC, dearshrewdwit commented on package.json
> +  },
Hm, cheeky, you rewrote history, so what can I say!

Originally, this was a comment on the additional `eslint` node packages that appeared here.

2021-08-24 14:03 UTC, OllieVanD commented on package.json
> +  },
I have added additional eslint node packages to the devdependencies, should they not be in the project?

2021-08-24 18:21 UTC, dearshrewdwit approved these changes
Ok. There's a bunch more work needed to refactor, but let's get this in now.

2021-08-24 18:21 UTC, dearshrewdwit commented on README.md
> +<<<<<<< HEAD
Still a couple remnants from an attempted conflict resolution to remove.

2021-08-24 18:21 UTC, dearshrewdwit commented on src/fileUpload.js
> +  headerChecker(headers) {
We'll come back to this to break this apart.

2021-08-24 18:22 UTC, dearshrewdwit reviewed
See comment re: conflict resolution

2021-08-25 08:44 UTC, Neokrieger approved these changes
LGTM

2021-08-25 08:57 UTC, dearshrewdwit approved these changes

2021-08-25 09:04 UTC, merged