AT-65-gender-dashboard-function
digital-futures-academy/atlas-api pull request #21
Opened 2021-08-24 14:04 UTC by b7rch4

Co-authored-by FractalFraction cln.gardiner@gmail.com

Jira: https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-65

Problem: We needed to create part of our API reponse which provides gender data for all students

Solution: We have created a function which makes a query to the database, and constructs the required section of the response.

No dependencies were harmed in the making of this pull request.

2021-08-24 14:29 UTC, dearshrewdwit requested changes
See below.

Where are the Cypress tests for this?

2021-08-24 14:29 UTC, dearshrewdwit commented on spec/unit/dashboard/backgroundObject.spec.js
>  const createCohorts = require('../../../test/ReportGroupTests/create-cohorts')
Is this needed?

2021-08-24 14:29 UTC, dearshrewdwit commented on spec/unit/dashboard/backgroundObject.spec.js
> +  it('calculates background ratio from background data', async () => {
The test description is the same as the above - can you name them accordingly?

2021-08-24 14:29 UTC, dearshrewdwit commented on spec/unit/dashboard/backgroundObject.spec.js
>    beforeEach( async () => {
do you need to truncate tables?

2021-08-24 14:44 UTC, FractalFraction commented on spec/unit/dashboard/backgroundObject.spec.js
>    beforeEach( async () => {
Yes, so the database is the same each time we run the unit test.

2021-08-24 14:44 UTC, FractalFraction commented on spec/unit/dashboard/backgroundObject.spec.js
> +  it('calculates background ratio from background data', async () => {
Yes, we will do that.

2021-08-24 14:47 UTC, dearshrewdwit commented on spec/unit/dashboard/backgroundObject.spec.js
>    beforeEach( async () => {
I didn't see the contracted lines - sorry!

2021-08-24 14:50 UTC, b7rch4 commented on spec/unit/dashboard/backgroundObject.spec.js
>  const createCohorts = require('../../../test/ReportGroupTests/create-cohorts')
I think we need to create cohorts because the when we create a student they have cohortId, which is a foreign key reference to the cohorts table

2021-08-24 15:45 UTC, dearshrewdwit commented on spec/unit/dashboard/backgroundObject.spec.js
>  const createCohorts = require('../../../test/ReportGroupTests/create-cohorts')
I see. Can you add a separate issue to the backlog not assigned to a team - creating a test task that creates Students and at the same time creating cohorts they belong to.

2021-08-24 15:46 UTC, dearshrewdwit commented
Where are the Cypress tests for this?

2021-08-24 16:47 UTC, b7rch4 commented
This PR doesn't feature Cypress tests for same reason at AT-62

2021-08-24 17:08 UTC, dearshrewdwit approved these changes

2021-08-25 08:04 UTC, richardtully approved these changes

2021-08-25 08:04 UTC, merged