Return the challenges of a student
digital-futures-academy/atlas-api pull request #29
Opened 2021-08-26 11:48 UTC by thekosiguy

.get('/:id') route also returns the challenges corresponding to a specific student.

2021-08-28 22:29 UTC, thekosiguy commented on routes/students.js
> +  const studentChallenges = await ModuleChallenge.findAll({
I've made the required changes, please review this pull request again.

2021-08-31 08:38 UTC, dearshrewdwit requested changes
Good. See comments

2021-08-31 08:38 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +    it('Retrieves data for a student with an id of 2', function(){
There is no benefit to having additional tests asserting on a successful request to the student endpoint.

What about if the student does not exist? What does the response look like?

2021-08-31 08:38 UTC, dearshrewdwit commented on package.json
> +    "cypress": "^8.3.1",
Please undo/remove from this PR - all dependency version upgrades should be on a separate PR

2021-08-31 08:38 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +            expect(res.body.student.ModuleChallenges[0].challengeName).to.eq('bank')
simplify:

```js
const bankChallenge = res.body.student.ModuleChallenges[0]

expect(bankChallenge.challengeName).to.eq('bank')
expect(bankChallenge.language).to.eq('node')
// etc
```

2021-08-31 13:39 UTC, thekosiguy commented on cypress/integration/studentInfo.spec.js
> +    it('Retrieves data for a student with an id of 2', function(){
fair enough, will work on that

2021-08-31 17:48 UTC, thekosiguy commented
Please review this PR again.

2021-08-31 18:06 UTC, thekosiguy commented
Doesn't null represent an empty object?

2021-09-01 08:25 UTC, dearshrewdwit requested changes

2021-09-01 08:25 UTC, dearshrewdwit commented on cypress/integration/studentInfo.spec.js
> +      expect(res.body.student).to.eq(null);
Change `null` to `{}`

2021-09-01 08:25 UTC, dearshrewdwit commented on routes/students.js
> +  res.json({ student: student });
Avoid relying on `null` values.
```js
const student = student || {}
res.json({ student: student });
```

2021-09-01 08:37 UTC, thekosiguy commented on cypress/integration/studentInfo.spec.js
> +      expect(res.body.student).to.eq(null);
did so yesterday lol just haven't pushed yet, will do that now

2021-09-01 13:03 UTC, dearshrewdwit approved these changes

2021-09-01 13:08 UTC, RyanVanDijck approved these changes

2021-09-01 13:08 UTC, merged