added gender migration column
digital-futures-academy/atlas-api pull request #3
Opened 2021-08-16 16:54 UTC by FractalFraction

2021-08-16 17:20 UTC, dearshrewdwit requested changes
Good. Thanks for keeping it small.

Can you:
- Add the Jira Issue link in the PR
- Add a brief description of the proposed change
- remove comments from the migration file
- remove `package-lock.json` from this commit: it shouldn't have changed, no dependencies were added

2021-08-17 08:29 UTC, FractalFraction commented
AT-20 Add gender column to the students Table.
A migration that adds a column on the students relation in the atlas-api. 

https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-20

2021-08-17 08:36 UTC, dearshrewdwit approved these changes

2021-08-17 09:35 UTC, b7rch4 approved these changes

2021-08-17 10:18 UTC, Reginmaru commented
Looks good.

2021-08-17 15:11 UTC, dearshrewdwit approved these changes

2021-08-17 15:21 UTC, b7rch4 approved these changes

2021-08-17 15:23 UTC, merged