AT-61-update-student
digital-futures-academy/atlas-api pull request #44
Opened 2021-09-01 12:49 UTC by bferenczy0

Added implementation so that the api handles a request to change data in the student database, with error catching in the case of a blank input and associated tests, and returns the updated student data.
Jira: https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?issueParent=10137&selectedIssue=AT-61

2021-09-01 13:51 UTC, dearshrewdwit requested changes
Nice so far

2021-09-01 13:51 UTC, dearshrewdwit commented on cypress/integration/students.spec.js
> +  it("updates student data", function() {
Let's rename this block of tests.

Group them in order by 
1. endpoint - (students, individual student), maybe into separate files
2. HTTP method - (GET, POST, PUT etc)
3. Scenario - (success, failure)

Use  `#describe()` to group tests.

Use `#it()` to assert what should be returned `

2021-09-01 13:51 UTC, dearshrewdwit commented on routes/students.js
> +  if (req.body[Object.keys(req.body)] === ""){
Let's start a bit more simply, and then spot opportunities for refactors
NB: Each of the following needs a corresponding test
> 1. return error if student doesn't exist
> 2. return error if req params don't exist
> 3. return error if update not successful (eg updating a text field over the character length limit)
> 4. return success if success

```js
// pseudocode
const permittedParams = ['firstName', 'lastName']
router.put("/:id", async function (req,res) {
  const student = await Student.findOne({where: {id:req.params.id}})
  if (student === null) {
    res.json({
      status: "failure",
      student: {},
      errors: "Missing record"
  } else if (!Object.keys(req.body).every(key => permittedParams.includes(key)) {
    res.json({
      status: "failure",
      student: {},
      errors: "Invalid params"
    }
  } else {
    student.update(req.body)
      .then(student => {
        res.json({
          status: "success",
          student: updatedStudent,
          errors: []
        })
     .catch(error => {
        res.json({
          status: "failure",
          student: {},
          errors: [error.message] // something like this?
        })
    }
  }
}
```

2021-09-01 13:51 UTC, dearshrewdwit commented on routes/students.js
> +  if (req.body[Object.keys(req.body)] === ""){
We might then be able to clean this up afterwards

2021-09-02 10:08 UTC, dearshrewdwit commented on cypress/integration/students.spec.js
> +    cy.request({
Do you have access to a hardcoded student id from the createStudent task?

2021-09-02 10:13 UTC, dearshrewdwit requested changes
Nice - thanks for covering the different cases in tests.

See comments

2021-09-02 10:13 UTC, dearshrewdwit commented on cypress/integration/students.spec.js
> +      expect(res.body.students[0].id).to.be.a("number");
Can we add an assertion on the name so we can see that it changes on a successful update?

2021-09-02 10:16 UTC, dearshrewdwit commented on cypress/integration/students.spec.js
> +    cy.request({
I checked - you don't. What about hardcoding student IDs in the cypress task, so you can use them in the test?

There's a tradeoff here - we're testing implicitly the `/api/students` endpoint, as well as the individual student endpoint - but your test is decoupled from knowing about specific student IDs.

In this case I would err on the side of only testing one endpoint, unless I can't get around it.

2021-09-02 10:57 UTC, bferenczy0 commented on cypress/integration/students.spec.js
> +    cy.request({
Did not realise you could hardcode an id in a cypress task, that does make things a lot easier

2021-09-02 11:11 UTC, bferenczy0 commented on cypress/integration/students.spec.js
> +      expect(res.body.students[0].id).to.be.a("number");
``
      cy.request({
      method: "PUT",
      url: "api/students/1",
      body: {firstName: "Fred"}
    }).then(res => {
      expect(res.body.status).to.eq("success");
      expect(res.body.student.firstName).to.eq("Fred");
```
Such as this or do you mean another test afterwards that gets api/students and tests for the new name?

2021-09-02 11:13 UTC, bferenczy0 commented on cypress/integration/students.spec.js
> +      expect(res.body.students[0].id).to.be.a("number");
```suggestion
      cy.request({
      method: "PUT",
      url: "api/students/1",
      body: {firstName: "Fred"}
    }).then(res => {
      expect(res.body.status).to.eq("success");
      expect(res.body.student.firstName).to.eq("Fred");
```

Such as this or do you mean another test afterwards that gets api/students and tests for the new name?

2021-09-02 11:22 UTC, dearshrewdwit commented on cypress/integration/students.spec.js
> +      expect(res.body.students[0].id).to.be.a("number");
tldr - it doesn't matter anymore if you're making 1 put request.

If you're no longer making 2 requests - the first request to get all the students, it doesn't matter as much - we can rely on looking at the task for the previous name to verify the update actually happens. If you were getting data first before updating, this extra assertion would have added confidence that the update is working as expected (decreasing reliance on how the students endpoint works)

2021-09-02 11:28 UTC, dearshrewdwit commented on routes/students.js
> +    res.json({
can you extract the response object?
```js
const response = {
  status: "failure",
  student: {},
  errors: ""
}
if (student === null) {
  response.error = "missing record"
  res.json(response);
}
```

2021-09-02 13:02 UTC, RyanVanDijck approved these changes

2021-09-02 13:02 UTC, merged