date field added to cohorts table
digital-futures-academy/atlas-api pull request #5
Opened 2021-08-17 10:12 UTC by AamirahV

Problem: Needed a date column inside the Cohorts table

Solution: Added a date column to Cohorts table using a migration file and sequelize

Jira issue: https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-3

2021-08-17 10:26 UTC, dearshrewdwit reviewed
Nice! Thanks for the small PR.

Quick question - see below

2021-08-17 10:26 UTC, dearshrewdwit commented on migrations/20210817094012-create-added-date-field-to-cohorts.js
> +     await queryInterface.addColumn(
Is there a reason for the args to be on separate lines?

2021-08-17 10:28 UTC, breeshidy commented on migrations/20210817094012-create-added-date-field-to-cohorts.js
> +     await queryInterface.addColumn(
No, just thought it was easier to read

2021-08-17 11:29 UTC, dearshrewdwit submitted a review, later dismissed

2021-08-17 16:19 UTC, dearshrewdwit requested changes
Nice. Good idea.

Remember - the project doesn't have a date column field yet, so you don't need to add the date column, remove it, and then add the start date column.

Simply add the startDate column!

2021-08-17 16:26 UTC, AamirahV commented
> Nice. Good idea.
> 
> Remember - the project doesn't have a date column field yet, so you don't need to add the date column, remove it, and then add the start date column.
> 
> Simply add the startDate column!

Done

2021-08-18 09:47 UTC, breeshidy commented
> @AamirahV let's get this merged. You need 1 more review

can i approve this @dearshrewdwit

2021-08-18 09:55 UTC, dearshrewdwit commented
2 reviews are needed - 1 internal and 1 external.

Internal - to your team (but not one of the PR authors)
External - any non-team member

2021-08-18 10:24 UTC, grantwhiteman approved these changes
Looks good

2021-08-18 11:13 UTC, dearshrewdwit approved these changes

2021-08-18 11:16 UTC, merged