AT-17 Student Sorting
digital-futures-academy/atlas-api pull request #7
Opened 2021-08-17 11:42 UTC by bferenczy0

Added in code that will sort the student database alphabetically by first name. Added cypress test for the student database. 

https://dfacademy.atlassian.net/jira/software/projects/AT/boards/4?selectedIssue=AT-17

2021-08-17 12:13 UTC, dearshrewdwit requested changes
Would the cypress test still pass if you didn't request sorted data from your table?

2021-08-17 12:19 UTC, dearshrewdwit commented on routes/students.js
> +  const students = await Student.findAll({ include: { all: true },order: [["firstName", "ASC"]]})
Let's be dynamic about this rather than hardcode column name and sort order.

Can you refer to these as variables, and declare them before the query, or better yet, fetch them from the request - we might want to request data from this endpoint sorted in different ways.

The default sort can be on first name, ascending 👍

2021-08-17 12:19 UTC, bferenczy0 commented
> Would the cypress test still pass if you didn't request sorted data from your table?

Yes because the test only inserts one data entry and checks as to whether the data entry has been created correctly.

2021-08-17 12:21 UTC, bferenczy0 commented on routes/students.js
> +  const students = await Student.findAll({ include: { all: true },order: [["firstName", "ASC"]]})
Okay I will make it so that the data can be requested to be sorted in various ways

2021-08-19 15:46 UTC, bferenczy0 commented
Updated files to provide testing for created students test for an order and student route no longer hard codes a sort as frontend now deals with the sort

2021-08-19 16:05 UTC, dearshrewdwit submitted a review, later dismissed

2021-08-20 09:18 UTC, dearshrewdwit approved these changes

2021-08-23 13:26 UTC, RyanVanDijck approved these changes
It all looks fine to me.

2021-08-24 09:05 UTC, dearshrewdwit approved these changes

2021-08-24 09:07 UTC, RyanVanDijck approved these changes
Looks fine to me.

2021-08-24 09:07 UTC, merged