Updated the api to handle request
digital-futures-academy/atlas-api pull request #9
Opened 2021-08-17 15:35 UTC by breeshidy

Problem: Update API to handle request to `/api/cohorts?sort=date&order=descending`

Solution: Added a Get Route to handle requests by passing the params

Jira: https://dfacademy.atlassian.net/browse/AT-9

2021-08-17 15:46 UTC, dearshrewdwit requested changes
See below!

2021-08-17 15:46 UTC, dearshrewdwit commented on cypress/integration/cohorts.spec.js
> +    it("returns cohorts to /api/cohorts?sort=date&order=descending", function () {
How is this one test ensuring the sort and order?

I suggest creating a few cohorts, and having a few tests to sort via name, date and order by ASC, DESC.

2021-08-17 15:46 UTC, dearshrewdwit commented on cypress/fixtures/cohorts.json
> +{
What's the purpose of this file?

2021-08-17 15:46 UTC, dearshrewdwit commented on app.js
> +const express = require("express");
This is a nodejs style change - if so, let's put this on a separate PR, use eslint, and enforce it!

Otherwise this will cause lots of changes to people's code as they go from single to double quotes and back again.

So for this PR, undo these style changes.

2021-08-17 15:46 UTC, dearshrewdwit commented on package.json
> +  "devDependencies": {
Nice. Let's put this on a separate PR though.

2021-08-17 15:46 UTC, dearshrewdwit commented on routes/cohorts.js
> +router.get("/", async function (req, res) {
Why are there two routes matching `GET` and `"/"` ?

2021-08-17 15:46 UTC, dearshrewdwit commented on migrations/20210817094012-create-added-date-field-to-cohorts.js
> +     'date',
Can we name this column `startDate` to avoid ambiguity

2021-08-17 15:50 UTC, breeshidy commented on migrations/20210817094012-create-added-date-field-to-cohorts.js
> +     'date',
yes, sure can

2021-08-17 16:17 UTC, breeshidy commented on cypress/fixtures/cohorts.json
> +{
This was us playing our with the test -- we will be sure to add it to our gitignore or probably delete it :)

2021-08-17 16:18 UTC, breeshidy commented on package.json
> +  "devDependencies": {
i am not sure what you mean -- should I create a pull request for updating cypress dependency?

2021-08-17 16:19 UTC, breeshidy commented on routes/cohorts.js
> +router.get("/", async function (req, res) {
Sorry forgot to delete it, we were just testing the difference

2021-08-17 16:20 UTC, dearshrewdwit commented on package.json
> +  "devDependencies": {
Yes, correct. It's not part of this bit of work.

2021-08-17 16:39 UTC, breeshidy commented on app.js
> +const express = require("express");
sorry it's the style of my vs code that automatically changed it but I have undone the changes now

2021-08-18 13:08 UTC, breeshidy commented on cypress/integration/cohorts.spec.js
> +    it("returns cohorts to /api/cohorts?sort=date&order=descending", function () {
This has now been done

2021-08-18 13:54 UTC, dearshrewdwit commented
@breeshidy if this needs a review, please share in code-review in discord 👍

2021-08-18 13:56 UTC, breeshidy commented
> @breeshidy if this needs a review, please share in code-review in discord 👍

Done

2021-08-18 14:03 UTC, dearshrewdwit requested changes
Good. Some more work needed.

See comments below.

2021-08-18 14:03 UTC, dearshrewdwit commented on routes/cohorts.js
> +  if(sort === undefined && order === undefined){
This if statement can be DRYed up.

How can you set some default values for `sort` and `order` so you can avoid the if statement?

2021-08-18 14:03 UTC, dearshrewdwit commented on test/create-cohort.js
> +    name: 'test cohort',
What's the reasoning to add a `,` here?

2021-08-18 14:03 UTC, dearshrewdwit commented on cypress/fixtures/cohorts.json
> +{
You marked this conversation as resolved, but the file is still here. What's the reasoning to keep it?

2021-08-18 14:35 UTC, breeshidy commented on routes/cohorts.js
> +  console.log("sort " + sort + " order " + order)
Done

2021-08-18 14:53 UTC, breeshidy commented on routes/cohorts.js
> +  console.log("sort " + sort + " order " + order)
Done

2021-08-18 14:57 UTC, breeshidy commented on test/create-cohort.js
> +    name: 'test cohort',
wanted to add the start date field

2021-08-18 14:58 UTC, breeshidy commented on package.json
> +}
i guess i mistakenly took the } out

2021-08-18 15:21 UTC, breeshidy commented on cypress/integration/cohorts.spec.js
> +describe("Cohorts", function () {
updated test to add 3 different cohorts

2021-08-19 08:19 UTC, breeshidy commented
> Good. Some more work needed.
> 
> See comments below.

2021-08-19 08:20 UTC, breeshidy commented
> Good. Some more work needed.
> 
> See comments below.

Hello, @dearshrewdwit, the changes are made now. Do I submit on code review again?

2021-08-19 08:26 UTC, dearshrewdwit requested changes
Nice. See comments below

2021-08-19 08:26 UTC, dearshrewdwit commented on routes/cohorts.js
> +  console.log('sort ' + sort + ' order ' + order)
Let's remove debugging statements

2021-08-19 08:26 UTC, dearshrewdwit commented on test/create-cohort.js
> +    startDate: '12/01/2021'
What format is this? 'DD/MM/YYYY' or 'MM/DD/YYYY'? 

How do you know?

2021-08-19 08:28 UTC, dearshrewdwit commented
> > Good. Some more work needed.
> > See comments below.
> 
> Hello, @dearshrewdwit, the changes are made now. Do I submit on code review again?

@breeshidy yes, whenever you are looking for a review, share back in code-review 👍

2021-08-19 08:30 UTC, breeshidy commented on routes/cohorts.js
> +  console.log('sort ' + sort + ' order ' + order)
yes,  sorry missed that

2021-08-19 08:33 UTC, breeshidy commented on test/create-cohort.js
> +    startDate: '12/01/2021'
Ehh according to Postgres -- the format is YYYY-MM-DD format, is this the right format? I will change the test to match it

2021-08-19 08:35 UTC, dearshrewdwit commented on test/create-cohort.js
> +    startDate: '12/01/2021'
Yes, but how does `'12/01/2021'` get parsed into Postgres' format YYYY-MM-DD?

2021-08-19 08:36 UTC, dearshrewdwit commented on test/create-cohort.js
> +    startDate: '12/01/2021'
Get visibility from data in your table or from sequelize after you've created the these records.

2021-08-19 08:38 UTC, breeshidy commented on test/create-cohort.js
> +    startDate: '12/01/2021'
Okay will adjust that now

2021-08-19 08:57 UTC, dearshrewdwit approved these changes
Ok. Good enough. @breeshidy 

1. Add an issue to your board to clarify what happens if you pass request parameters that are not valid. eg: `?sort=XYZ&order=ABC` (it might be nothing, and simply reverts to the default behaviour. This should be documented.

2. In future please force squash your commits -> https://github.com/digital-futures-academy/atlas-api/pull/9/commits so that it reads easily as the history of change for this piece of work - currently it's hard to understand what happened!

2021-08-19 10:12 UTC, breeshidy commented
> Ok. Good enough. @breeshidy
> 
> 1. Add an issue to your board to clarify what happens if you pass request parameters that are not valid. eg: `?sort=XYZ&order=ABC` (it might be nothing, and simply reverts to the default behaviour. This should be documented.
> 2. In future please force squash your commits -> https://github.com/digital-futures-academy/atlas-api/pull/9/commits so that it reads easily as the history of change for this piece of work - currently it's hard to understand what happened!



> 2\. please force squash your commits

Hello

> Ok. Good enough. @breeshidy
> 
> 1. Add an issue to your board to clarify what happens if you pass request parameters that are not valid. eg: `?sort=XYZ&order=ABC` (it might be nothing, and simply reverts to the default behaviour. This should be documented.
> 2. In future please force squash your commits -> https://github.com/digital-futures-academy/atlas-api/pull/9/commits so that it reads easily as the history of change for this piece of work - currently it's hard to understand what happened!

Hello Ed, I have now added the issue section now. 

> Ok. Good enough. @breeshidy
> 
> 1. Add an issue to your board to clarify what happens if you pass request parameters that are not valid. eg: `?sort=XYZ&order=ABC` (it might be nothing, and simply reverts to the default behaviour. This should be documented.
> 2. In future please force squash your commits -> https://github.com/digital-futures-academy/atlas-api/pull/9/commits so that it reads easily as the history of change for this piece of work - currently it's hard to understand what happened!

1-> I have added the issue section of the code and updated it to catch the error and test for invalid inputs

2-> In terms of the squash command. I have tried to google it but I do not seem to understand it. please could you provide steps on how to use it?

2021-08-19 10:28 UTC, dearshrewdwit requested changes
Almost there.

Remember - design behaviour, **codify it** in a **test**, and then write source code.

2021-08-19 10:28 UTC, dearshrewdwit commented on routes/cohorts.js
> +    res.json({ errors: "Sorry invalid query parameters" })
Where's the test for this error message?

2021-08-19 10:30 UTC, dearshrewdwit commented on routes/cohorts.js
> +    res.json({ errors: "Sorry invalid query parameters" })
Remember: on the front end you'll need to have a component that can handle a response object like this

2021-08-19 10:55 UTC, dearshrewdwit approved these changes

2021-08-19 10:59 UTC, dearshrewdwit approved these changes

2021-08-19 11:05 UTC, breeshidy commented on routes/cohorts.js
> +    res.json({ errors: "Sorry invalid query parameters" })
we have added the test and it will return an array of errors

2021-08-19 11:08 UTC, Reginmaru submitted a review, later dismissed

2021-08-19 11:19 UTC, breeshidy commented on routes/cohorts.js
> +    res.json({ errors: "Sorry invalid query parameters" })
@dearshrewdwit , I think I messed up something with my commit, please can you have a look and see?

2021-08-19 11:28 UTC, dearshrewdwit commented
@breeshidy there were two approvals from me and @Reginmaru .... 
> breeshidy dismissed stale reviews from Reginmaru and dearshrewdwit via 5b9bdad 16 minutes ago

2021-08-19 11:28 UTC, dearshrewdwit approved these changes

2021-08-19 16:29 UTC, Reginmaru submitted a review, later dismissed

2021-08-19 17:35 UTC, dearshrewdwit approved these changes

2021-08-20 08:48 UTC, Reginmaru approved these changes

2021-08-20 08:50 UTC, merged